import { Outfit, Ubuntu_Mono } from 'next/font/google'
import localFont from 'next/font/local'
import '@/app/assets/css/globals.css'
import { ReactElement } from 'react'

import type { Metadata } from 'next'

const outfit = Outfit({
  subsets: ['latin'],
  display: 'swap',
})

const ubuntuMono = Ubuntu_Mono({
  weight: '700',
  subsets: ['latin'],
  variable: '--font-ubuntu-mono',
})

const geistSans = localFont({
  src: './assets/fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './assets/fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: `Violet's Work`,
  description: 'Generated by create next app',
}

type RootLayoutProps = { children: ReactElement; params: Promise<{ lng: string }> }

export default async function RootLayout({ children, params }: RootLayoutProps) {
  const { lng } = await params
  return (
    <html lang={lng}>
      <body
        // 防止chrome擴充功能影響程式碼
        suppressHydrationWarning={true}
        className={`${outfit.className} ${ubuntuMono.variable} ${geistSans.variable} ${geistMono.variable} antialiased dark:bg-black dark:text-white`}
      >
        {children}
      </body>
    </html>
  )
}
