import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'
import { ReactElement } from 'react'

import { Footer } from '@/app/componments/footer'
import { Header_resume } from '@/app/componments/header'

import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: `Violet's Work`,
  description: 'Generated by create next app',
}

type RootLayoutProps = { children: ReactElement; params: Promise<{ lng: string }> }
export default async function Layout({ children, params }: RootLayoutProps) {
  const { lng } = await params

  const messages = await getMessages()
  return (
    <>
      <NextIntlClientProvider messages={messages}>
        <Header_resume lng={lng} />
        {children}
        <Footer />
      </NextIntlClientProvider>
    </>
  )
}
