import type { Metadata } from 'next'
import { Header_resume } from '@/app/_componments/header'
import { Footer } from '@/app/_componments/footer'

import { ReactElement } from 'react'

import { languages } from '@/i18n/settings'

export const metadata: Metadata = {
    title: `Violet's Work`,
    description: 'Generated by create next app',
}

type RootLayoutProps = { children: ReactElement; params: Promise<{ lng: string }> }
export default async function Layout({ children, params }: RootLayoutProps) {
    const resolvedParams = await params
    return (
        <>
            <Header_resume lng={resolvedParams.lng} />
            {children}
            <Footer />
        </>
    )
}
